version: 0.2

phases:
  install:
    commands:
      - echo ===> Installing node 12 for Ubuntu ...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo ===> Installing dependencies ...
      - npm i
  build:
    commands:
      - echo ===> Testing
      - echo ===> Building
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
